# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s 

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
#Default
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
#Node Exporter
  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    static_configs:
    - targets: ['nginx-exporter:9113']
#Nginx Exporter
  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
    - targets: ['node-exporter:9100']
#Docker cadvisor
  - job_name: 'Docker'
    scrape_interval: 15s
    static_configs:
    - targets: ['cadvisor:8080']

